### ISSUE TITLE
AttributeError: 'csc_matrix' object has no attribute 'A'

### ISSUE THREAD

**Issue by fusca9** [bioinfo-biols/SEVtras#32]
Dear Author,
i'm using this script for analysis:
import SEVtras
SEVtras.sEV_recognizer(
    input_path='/mnt/data1/foschi',  
    sample_file='/mnt/data1/foschi/sample_file.txt',  
    out_path='/mnt/data1/foschi/outputs_SEVtras',
    species='Homo'
)
the output directories of cellranger are in: /mnt/data1/foschi and the file .txt is in this path: '/mnt/data1/foschi/sample_file.txt.
However, i encountered this error: 
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/data1/foschi/script_SEVtras.py", line 4, in <module>
    SEVtras.sEV_recognizer(
  File "/home/foschi/.local/lib/python3.10/site-packages/SEVtras/main.py", line 121, in sEV_recognizer
    inter_adata, iteration_list = iteration(inter_adata, iteration_list, thershold, max_M, threads=threads, number_g = 30, alpha = alpha)
  File "/home/foschi/.local/lib/python3.10/site-packages/SEVtras/utils.py", line 204, in iteration
    result_tmp = multi_cor(inter_adata, threads)
  File "/home/foschi/.local/lib/python3.10/site-packages/SEVtras/utils.py", line 173, in multi_cor
    result_tmp = pool.map(corr_genes, item_list)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
AttributeError: 'csc_matrix' object has no attribute 'A'.
i don't know why this error occurs, i followed all the instructions on the website. Do you know what is going wrong? Can ypu please give me some advice? Thank you very much for your work!

**Comment by RuiqiaoHe** [comment]
The error may be due to mismatched format in the input data files (different from 10X CellRanger standard output). It is OK to format each dataset in the `sample_file.txt` with the following code:
`import anndata as ad`
`from scipy.sparse import csr_matrix`
`adata = ad.read_h5ad('./adata.h5ad')`
`adata.X = csr_matrix(adata.X)`
`adata.write_h5ad('./adata_s.h5ad')`
The generated `adata_s.h5ad` would be used as the input files.

**Comment by fusca9** [comment]
Thank you for the quick answer! however i used 10XCellRanger standard outputs(raw_feature_bc_matrix) as inputs for SEVtras. Anyway i'll try your suggestion!

**Comment by RuiqiaoHe** [comment]
This is not normal. Could you please first try to run the test data located at https://github.com/bioinfo-biols/SEVtras/tree/main/tests? It would only take a few minutes.

**Comment by fusca9** [comment]
i'm sorry for the late answer. i had a problem with th server but now it works and i could achieve finishing the SEVtras.sEV_recognizer analysis. Thank you very much.
i would ask only one last question. The input for SEVtras.ESAI_calculator consists of a cell matrix with cell type, but how can i create this matrix? what kind of data i need?
sorry if i'm not very into english and thank you for the help!

**Comment by RuiqiaoHe** [comment]
SEVtras needs the cell matrix in h5ad format, this can be converted by `scanpy` with the following code:
`import scanpy as sc`
`adata = = sc.read_10x_h5(path)#path means the directory of feature_bc_matrix`
`adata.write_h5ad('./adata.h5ad')`
And the cell type information, this is conventional analysis in the single cell transcriptomics. You can refer to [here](https://scanpy.readthedocs.io/en/stable/tutorials/basics/clustering-2017.html) for further insights.
