### ISSUE TITLE
ValueError: Length mismatch in deconvolver

### ISSUE THREAD

**Issue by WhaleGe** [bioinfo-biols/SEVtras#5]
Thank you very much for the tool you developed. But an error occurred when I applied it to calculate ESAI. I ruled out many possibilities, but still could not solve the problem. Can you take a look at it for me when you have time?

> Traceback (most recent call last):
  File "./SEVtras/calculator.py", line 55, in <module>
    SEVtras.ESAI_calculator(adata_ev_path='SEVtras/sEV_SEVtras_231219.h5ad', adata_cell_path='SEVtras/hm_Patient_hvg3000_PC30_res1_dist0.1_k20_S0_rawcount_231219.h5ad', out_path='SEVtras', Xraw=False, OBSsample='Sample', OBScelltype='subtype')
  >File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/SEVtras/main.py", line 187, in ESAI_calculator
    celltype_e_number, adata_evS, adata_com = deconvolver(adata_ev, adata_cell, OBSsample, OBScelltype, OBSev, OBSMpca, cellN, Xraw, normalW)
  File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/SEVtras/functional.py", line 128, in deconvolver
    **near_neighbor_dat.index = adata_ev.obs.index**
  File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/pandas/core/generic.py", line 5500, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 70, in pandas._libs.properties.AxisProperty.__set__
  File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/pandas/core/generic.py", line 766, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 216, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/Mn/conda/envs/sevtras/lib/python3.7/site-packages/pandas/core/internals/base.py", line 58, in _validate_set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
**ValueError: Length mismatch:** Expected axis has 135224 elements, new values have 144325 elements

**Comment by RuiqiaoHe** [comment]
Please first check the version of SEVtras is at v0.2.8. 
If it's already this version, this problem may be caused by the dimension of the input cell matrix not matching the SEV matrix in some samples. SEVtras deconvolver needs the corresponding sample information in the input cell matrix for each sEV. Thus, please check that the sample name in the sEV matrix matches the sample name in the cell matrix (this should be contained in adata.obs, default is key 'batch' in the sEV matrix and cell matrix).

**Comment by WhaleGe** [comment]
> Please first check the version of SEVtras is at v0.2.8. If it's already this version, this problem may be caused by the dimension of the input cell matrix not matching the SEV matrix in some samples. SEVtras deconvolver needs the corresponding sample information in the input cell matrix for each sEV. Thus, please check that the sample name in the sEV matrix matches the sample name in the cell matrix (this should be contained in adata.obs, default is key 'batch' in the sEV matrix and cell matrix).

Thank you very much. I found that there are two missing samples in cell matrix. There is a difference between batch in sev matrix and cell matrix. Thanks for the tip your provided
